# -*- coding: utf-8 -*-
"""wave.fm ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16QvennPpTJoWcK4hF6gyAi5xnKS4D73h

# Batch offline embedding pipeline (Colab, T4)
This notebook implements the following deterministic pipeline:
- read `manifest.jsonl` (title + artist)
- for each item: find top YouTube hit, dedupe by `yt:VIDEOID`, download exact VIDEOID → 24k float32 mono WAV, split into 30s chunks, run MuQ-MuLan in batches of windows, mean-pool per-song embeddings, write `songs.jsonl` then append `processed.jsonl`. Failures are recorded with `title`/`artist`.

## Install Prerequisites
"""

# Commented out IPython magic to ensure Python compatibility.
# Install system and Python dependencies.
# - ffmpeg for transcoding
# - muq (MuQ-MuLan wrapper), yt-dlp, librosa, soundfile, numpy, tqdm, pandas

# Run apt-get for ffmpeg
!apt-get update -y
!apt-get install -y ffmpeg

# Python packages (muq will fetch model checkpoints from Hugging Face when used).
# yt-dlp is installed from PyPI; import name is `yt_dlp`.
# %pip install -q muq yt-dlp librosa soundfile numpy tqdm pandas chromadb

import torch
print("Installed torch:", torch.__version__, "cuda_available:", torch.cuda.is_available())

"""## Imports"""

# Imports and constants
import os, json, math, time, datetime
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Dict, Tuple, Optional
import numpy as np
import librosa
import soundfile as sf
from tqdm.notebook import tqdm
from muq import MuQMuLan
from yt_dlp import YoutubeDL
import os
from google.colab import userdata
import requests
import random
from transformers import XLMRobertaTokenizer

"""# Constants"""

# Pipeline constants (tune as needed)
SR = 24000
CHUNK_SECONDS = 30
OVERLAP_SECONDS = 7.5
MAX_TOKENS = 512
SAMPLES_PER_CHUNK = SR * CHUNK_SECONDS  # 720000
WINDOW_SIZE = 16          # windows per GPU forward pass
DEFAULT_K = 16             # songs per job
DOWNLOAD_CONCURRENCY = 3  # parallel downloads
RETRY_DOWNLOADS = 2       # retries for download/transcode
TMP_ROOT = Path("/tmp/embed_job")
TMP_ROOT.mkdir(parents=True, exist_ok=True)

# Filenames (you can change these paths)
MANIFEST_PATH = Path("manifest.jsonl")
PROCESSED_PATH = Path("processed.jsonl")
SONGS_PATH = Path("songs.jsonl")

"""## Helpers"""

# JSONL helpers: read list (manifest), append atomic line (ledger), safe write
def read_jsonl(path: str) -> List[Dict]:
    if not os.path.exists(path):
        return []
    with open(path, "r", encoding="utf8") as f:
        return [json.loads(line) for line in f if line.strip()]

def append_jsonl(path: str, obj: Dict):
    # append a single JSON line and fsync to reduce chance of data loss
    with open(path, "a", encoding="utf8") as f:
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")
        f.flush()
        try:
            os.fsync(f.fileno())
        except Exception:
            pass

def write_jsonl_atomic(path: str, objs: List[Dict]):
    # safely append lines to path
    with open(path, "w", encoding="utf8") as f:
        for obj in objs:
            f.write(json.dumps(obj, ensure_ascii=False) + "\n")
        f.flush()
        try:
            os.fsync(f.fileno())
        except Exception:
            pass

"""## Get Last.fm top tracks"""

# Preferred way to read Colab-managed secrets; fall back to environment variables for non-Colab runs
def get_secret(name: str):
    v = userdata.get(name)
    if v is None:
        v = os.getenv(name)
    return v

LAST_FM_API_KEY = get_secret("LAST_FM_API_KEY")

def get_lastfm_top_tracks(n: int = 100):
    key = get_secret("LAST_FM_API_KEY")
    url = f"http://ws.audioscrobbler.com/2.0/?method=chart.gettoptracks&api_key={key}&format=json&limit={n}"
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    data = r.json()
    tracks = [
        {"title": track["name"], "artist": track["artist"]["name"]}
        for track in data["tracks"]["track"]
    ]
    return tracks

tracks = get_lastfm_top_tracks(100) # max 1000
write_jsonl_atomic(MANIFEST_PATH, tracks)

"""## Get lyrics from LRCLib"""

import re

def normalize_whitespace(text: str) -> str:
    # replace multiple spaces or tabs with a single space
    text = re.sub(r'[ \t]+', ' ', text)
    # remove leading/trailing spaces for each line
    text = '\n'.join(line.strip() for line in text.splitlines())
    return text

def collapse_newlines(text: str) -> str:
    # replace 2+ newlines with a single newline
    return re.sub(r'\n{2,}', '\n', text)

def clean_lyrics(text: str) -> str:
    text = normalize_whitespace(text)
    text = collapse_newlines(text)
    # final strip to remove any leading/trailing newlines
    return text.strip()

import requests
from typing import Optional
import re

def get_lyrics(
    title: str,
    artist: str,
) -> Optional[str]:
    """
    Search LRCLIB /api/search for the given title and artist and return the plainLyrics
    of the best-matching result. If plainLyrics is missing but syncedLyrics exists,
    a plain-text version is returned by stripping timestamp tags.

    Returns:
      - plain lyrics string if found
      - None if no match or no lyrics found (unless raise_on_missing True, then raises)
    """
    url = "https://lrclib.net/api/search"

    params = {
        "track_name": title,
        "artist_name": artist,
    }
    headers = {
        "User-Agent": "lrclib-client/0.1 (wave.fm)"
    }

    resp = requests.get(url, params=params, headers=headers, timeout=10)
    time.sleep(0.1 + random.random() * 0.1) # Polite delay to prevent overloading API
    resp.raise_for_status()
    results = resp.json()

    if not isinstance(results, list) or len(results) == 0:
        return None

    best = results[0]
    lyrics = best.get("plainLyrics")
    if lyrics:
        return clean_lyrics(lyrics)

    # fallback: if syncedLyrics exists, strip timestamps like [00:17.12] to form plain text
    lyrics = best.get("syncedLyrics")
    if lyrics:
        lyrics = re.sub(r"\[\d{2}:\d{2}(?:\.\d{1,3})?\]\s*", "", lyrics).strip()
        if lyrics:
            return clean_lyrics(lyrics)

    return None

lyrics = get_lyrics("here comes the sun", "beatles")
if lyrics:
    print(lyrics)
else:
    print("No lyrics found")

"""## Download WAV from YouTube"""

# Use yt_dlp to search top metadata-only result (no download).
# returns dict {id,title,duration,webpage_url} or None
def youtube_search_top(title: str, artist: str, timeout: int = 30) -> Optional[Dict]:
    q = f"{title} - {artist}"
    ydl_opts = {
        "quiet": True,
        "skip_download": True,
        "noplaylist": True,
        # extract only the first result of a search ('ytsearch1:')
        # we'll call extract_info with the 'ytsearch1:' prefix below
    }
    try:
        with YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(f"ytsearch1:{q}", download=False)
            # yt-dlp returns a dictionary with 'entries' when searching
            entry = None
            if info is None:
                return None
            if "entries" in info:
                entries = info.get("entries", [])
                if not entries:
                    return None
                entry = entries[0]
            else:
                entry = info
            if not entry:
                return None
            # return normalized metadata
            return {
                "id": entry.get("id"),
                "title": entry.get("title"),
                "duration": entry.get("duration"),
                "webpage_url": entry.get("webpage_url")
            }
    except Exception as e:
        # treat as no result for robust behavior; caller may log the exception in reason
        return None

import subprocess
from pathlib import Path

def convert_to_wav(input_path: Path, output_path: Path, sr=24000):
    cmd = [
        "ffmpeg",
        "-y",  # overwrite if exists
        "-i", str(input_path),
        "-ar", str(sr),
        "-ac", "1",
        "-c:a", "pcm_f32le",  # use 32-bit float PCM
        str(output_path)
    ]
    subprocess.run(cmd, check=True)
    return output_path

# Download a specific video id and transcode to 24 kHz float32 mono WAV.
# Returns absolute path to WAV on success, raises on failure.
def download_video_to_wav(video_id: str, out_dir: Path, retries:int = RETRY_DOWNLOADS) -> str:
    out_dir.mkdir(parents=True, exist_ok=True)
    out_template = str(out_dir / f"{video_id}.%(ext)s")
    url = f"https://www.youtube.com/watch?v={video_id}"
    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": out_template,
        "quiet": True,
        #"verbose": True,
        "noplaylist": True,
        # do not write metadata files
        "writethumbnail": False,
        "cookies": "/content/cookies.txt", # IMPORTANT: YT-DLP needs this to download videos for some reason
    }

    last_exc = None
    for attempt in range(1, retries+2):  # retries attempts + initial
        try:
            with YoutubeDL(ydl_opts) as ydl:
                ydl.download([url])

            # Convert manually
            webm_path = out_dir / f"{video_id}.webm"
            wav_path = out_dir / f"{video_id}.wav"
            convert_to_wav(webm_path, wav_path)


            if wav_path.exists():
                return wav_path
            else:
                raise RuntimeError(f"ffmpeg output not found at {wav_path}")
        except Exception as e:
            last_exc = e
            if attempt <= retries:
                # brief backoff
                time.sleep(1.0 * attempt)
                continue
            else:
                raise last_exc

"""## Chunk WAV"""

# Load a wav file (assumed 24k float32 mono), split into 30s chunks, pad last chunk with zeros.
# Returns list of chunk dicts: {song_id, title, artist, chunk_idx, start_time, waveform(np.float32)}
def load_wav_and_chunk(wav_path: str, song_id: str, title: str, artist: str) -> List[Dict]:
    wav, sr = librosa.load(wav_path, sr=SR, mono=True)  # returns float32
    T = wav.shape[0]
    chunks = []
    chunks_count = math.ceil(T / SAMPLES_PER_CHUNK)
    for chunk_idx in range(chunks_count):
        start = chunk_idx * SAMPLES_PER_CHUNK
        end = min(start + SAMPLES_PER_CHUNK, T)
        chunk = wav[start:end]
        if chunk.shape[0] < SAMPLES_PER_CHUNK:
            # pad with zeros to exactly SAMPLES_PER_CHUNK
            pad_len = SAMPLES_PER_CHUNK - chunk.shape[0]
            chunk = np.pad(chunk, (0, pad_len), mode="constant").astype(np.float32)
        else:
            chunk = chunk.astype(np.float32)
        chunks.append({
            "song_id": song_id,
            "title": title,
            "artist": artist,
            "chunk_idx": chunk_idx,
            "start_time": start / SR,
            "waveform": chunk
        })
    return chunks

"""## Model Helpers"""

# Model load (once per runtime)
def load_mulan(device: str = "cuda"):
    device = device if torch.cuda.is_available() else "cpu"
    mulan = MuQMuLan.from_pretrained("OpenMuQ/MuQ-MuLan-large")  # downloads checkpoint from HF if necessary
    mulan = mulan.to(device).eval()
    return mulan, device

# Run a batch of waveforms (numpy arrays of shape [SAMPLES_PER_CHUNK]) through MuQ-MuLan
# returns numpy array [batch, D]
def mulan_infer_batch(mulan, device, waveforms: List[np.ndarray]) -> np.ndarray:
    # stack, convert to torch.float32 tensor
    batch = np.stack(waveforms, axis=0)
    batch_t = torch.from_numpy(batch).to(device=device, dtype=torch.float32)
    with torch.no_grad():
        emb_t = mulan(wavs=batch_t)  # per example usage
    # ensure CPU numpy
    return emb_t.cpu().numpy()

# L2-normalize (optional)
def l2_normalize(vec: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    norm = np.linalg.norm(vec)
    if norm < eps:
        return vec
    return vec / norm

# Mean-pool list of embeddings
def mean_pool_embeddings(embs_list: List[np.ndarray], l2_norm: bool = False) -> np.ndarray:
    if not embs_list:
      return np.zeros((1,), dtype=np.float32)
    stacked = np.stack(embs_list, axis=0)
    mean_vec = np.mean(stacked, axis=0)
    if l2_norm:
        mean_vec = l2_normalize(mean_vec)
    return mean_vec

"""## Song Data Class Definition and Ingestion

Monkey-patch mulan.mulan.text.forward to handle tokenized inputs
"""

import types

def patched_forward(self, x=None, raw_texts=None, mask=None, return_all_layers=False, return_mean=True):
    """
    Monkey-patched forward to handle both raw_texts and already-tokenized input.
    """
    assert (x is not None) ^ (raw_texts is not None), "Provide only one of x or raw_texts"
    with torch.no_grad():
        if raw_texts is not None:
            # Standard path: let model handle tokenization
            inputs = self.tokenizer(
                raw_texts,
                return_tensors='pt',
                padding='max_length',
                truncation=True,
                max_length=self.max_seq_len
            )
            inputs = inputs.to(self.device)
            if mask is not None:
                inputs['attention_mask'] = mask
            outputs = self.pred_pretrained_model_hidden(**inputs)
        elif x is not None:
            # Already-tokenized path
            inputs = {'input_ids': x}
            if mask is not None:
                inputs['attention_mask'] = mask
            outputs = self.pred_pretrained_model_hidden(**inputs)
        else:
            raise ValueError("Either x or raw_texts must be provided.")

    outputs = self.proj(outputs)
    outputs, layer_results = self.transformer(outputs, return_all_layers=True)
    if return_mean:
        outputs = outputs.mean(dim=-2)
    if return_all_layers:
        return outputs, layer_results
    return outputs

import datetime
import os
import random
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import librosa
import numpy as np
import torch
from tqdm import tqdm

@dataclass
class SongData:
    """A lean, centralized data structure for tracking the final state of a song."""
    # Core identifiers from the manifest
    title: str
    artist: str

    # The stable, unique ID for tracking this song
    song_id: Optional[str] = None

    # Flags to control the processing pipeline
    process_audio: bool = False
    process_lyrics: bool = False

    # Final state and data
    audio_status: str = "pending"
    lyrics_status: str = "pending"
    audio_embedding: Optional[np.ndarray] = None
    lyrics_text: Optional[str] = None
    lyrics_embedding: Optional[np.ndarray] = None
    duration: Optional[float] = None
    num_chunks: Optional[int] = None
    failure_reason: Optional[str] = None

    def to_song_record(self) -> Dict[str, Any]:
        """Converts the final data to a dictionary for songs.jsonl."""
        audio_emb_list = self.audio_embedding.astype(float).tolist() if self.audio_embedding is not None else None
        lyrics_emb_list = self.lyrics_embedding.astype(float).tolist() if self.lyrics_embedding is not None else None
        return {
            "song_id": self.song_id,
            "title": self.title,
            "artist": self.artist,
            "duration": self.duration,
            "num_chunks": self.num_chunks,
            "audio_embedding": audio_emb_list,
            "lyrics": self.lyrics_text,
            "lyrics_embedding": lyrics_emb_list,
            "processed_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        }

def _normalize_string(s: str) -> str:
    """Normalizes a string for use in a fallback ID."""
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")

def identify_songs_to_process(
    manifest: List[Dict],
    processed_statuses: Dict[str, Dict[str, str]]
) -> List[SongData]:
    """Identifies songs that need processing and creates a stable ID for them."""
    songs_to_process = []
    print("Identifying songs for processing...")
    for entry in tqdm(manifest, desc="Checking manifest"):
        title = entry.get("title")
        artist = entry.get("artist")
        song = SongData(title=title, artist=artist)

        # 1. Attempt to find on YouTube to get the primary ID
        yt_meta = youtube_search_top(title, artist)

        if yt_meta and yt_meta.get("id"):
            song.song_id = f"yt:{yt_meta['id']}"
        else:
            # 2. Create a stable fallback ID if YouTube search fails
            normalized_id = f"{_normalize_string(artist)}-{_normalize_string(title)}"
            song.song_id = f"local:{normalized_id}"
            # As requested, only audio processing is impossible without a source
            song.audio_status = "failed"
            song.failure_reason = "youtube_no_result"
            print(f"[Info] No YouTube result for '{title}'. Will attempt lyrics processing with ID {song.song_id}")

        # 3. Check status and decide what to process
        status = processed_statuses.get(song.song_id)
        if status and status.get("audio_status") == "done" and status.get("lyrics_status") == "done":
            continue

        # Determine if audio needs processing (it must not have failed from the start)
        song.process_audio = (song.audio_status != "failed") and not (status and status.get("audio_status") == "done")

        # Determine if lyrics need processing
        song.process_lyrics = not (status and status.get("lyrics_status") == "done")

        if song.process_audio or song.process_lyrics:
            songs_to_process.append(song)

    return songs_to_process

def download_audio(songs: List[SongData], tmp_dir: Path, concurrency: int) -> Dict[str, Path]:
    """Downloads audio files and returns a map of song_id -> wav_path."""
    songs_to_download = [s for s in songs if s.process_audio]
    if not songs_to_download:
        return {}

    song_to_wav_path = {}

    def _dl_task(song: SongData):
        try:
            video_id = song.song_id.split(":")[-1]
            wav_path = download_video_to_wav(video_id, tmp_dir, retries=RETRY_DOWNLOADS)
            return song, wav_path, None
        except Exception as e:
            return song, None, e

    with ThreadPoolExecutor(max_workers=concurrency) as ex:
        futures = {ex.submit(_dl_task, song): song for song in songs_to_download}
        for fut in tqdm(as_completed(futures), total=len(futures), desc="Downloading"):
            song, wav_path, error = fut.result()
            if error:
                song.audio_status = "failed"
                song.failure_reason = song.failure_reason or f"download_failed: {error}"
            else:
                song_to_wav_path[song.song_id] = wav_path

    return song_to_wav_path

def compute_audio_embeddings(mulan, device, songs: List[SongData], song_to_wav_path: Dict[str, Path], window_size: int, l2_norm: bool):
    """Computes audio embeddings for successfully downloaded songs."""
    songs_with_audio = [s for s in songs if s.song_id in song_to_wav_path]
    if not songs_with_audio:
        return

    all_chunks = []

    # 1. Load audio and create a flat list of all chunks
    for song in songs_with_audio:
        wav_path = song_to_wav_path[song.song_id]
        try:
            chunks = load_wav_and_chunk(wav_path, song.song_id, song.title, song.artist)
            song.duration = librosa.get_duration(path=wav_path)
            song.num_chunks = len(chunks)
            all_chunks.extend(chunks)
        except Exception as e:
            song.audio_status = "failed"
            song.failure_reason = f"chunking_failed: {e}"

    # 2. Process all chunks in batches for efficiency
    song_embeddings_map = {s.song_id: [] for s in songs_with_audio}
    for i in tqdm(range(0, len(all_chunks), window_size), desc="Audio Embedding"):
        batch_meta = all_chunks[i:i + window_size]
        waveforms = [m["waveform"] for m in batch_meta]
        emb_batch = mulan_infer_batch(mulan, device, waveforms)
        for j, meta in enumerate(batch_meta):
            song_embeddings_map[meta["song_id"]].append(l2_normalize(emb_batch[j]))

    # 3. Pool embeddings and update the SongData objects
    for song in songs_with_audio:
        if song.audio_status != "failed":
            embs = song_embeddings_map.get(song.song_id)
            if embs:
                song.audio_embedding = mean_pool_embeddings(embs, l2_norm=l2_norm)
                song.audio_status = "done"
            else:
                song.audio_status = "failed"
                song.failure_reason = song.failure_reason or "no_embeddings_generated"

def run_ingestion_pipeline(
    manifest_path: Path = MANIFEST_PATH,
    processed_path: Path = PROCESSED_PATH,
    songs_path: Path = SONGS_PATH,
    k: int = DEFAULT_K,
    window_size: int = WINDOW_SIZE,
    download_concurrency: int = DOWNLOAD_CONCURRENCY,
    tmp_root: Path = TMP_ROOT,
    l2_norm: bool = True,
):
    """
    Process the manifest in batches of size `k`. For each batch:
      - create a per-batch tmp dir
      - download audio -> compute audio embeddings -> compute lyrics embeddings
      - save results and cleanup wav files for that batch
    The model (mulan) is loaded once and reused across batches.
    """
    tmp_root.mkdir(parents=True, exist_ok=True)

    # Load model once
    mulan, device = load_mulan()
    print(f"Model loaded on {device}.")
    tokenizer = XLMRobertaTokenizer.from_pretrained("xlm-roberta-base")
    print("XLMRobertaTokenizer loaded.")

    # Monkey-patch for TextTransformerPretrained to handle forward properly
    text_transformer = mulan.mulan.text  # Should be a TextTransformerPretrained instance
    text_transformer.forward = types.MethodType(patched_forward, text_transformer)

    # Read manifest and prepare batches
    full_manifest = read_jsonl(manifest_path)
    if not full_manifest:
        print("Manifest is empty.")
        return

    total = len(full_manifest)
    batches = (total + k - 1) // k  # ceil division

    for batch_idx in tqdm(range(batches), desc="Processing batches", unit="batch"):
        start = batch_idx * k
        end = min(start + k, total)
        batch_manifest = full_manifest[start:end]
        print(f"\nBatch {batch_idx + 1}/{batches} — items {start}:{end} (count={len(batch_manifest)})")

        # Reload processed statuses to skip already-processed items
        processed_statuses = load_processed_statuses(processed_path)
        songs_to_process = identify_songs_to_process(batch_manifest, processed_statuses)

        if not songs_to_process:
            print(f"Batch {batch_idx + 1}: no songs to process (all already done).")
            continue

        batch_tmp = tmp_root / f"job_{batch_idx}_{int(time.time())}"
        batch_tmp.mkdir(parents=True, exist_ok=True)

        try:
            # song_to_wav_path: Dict[str, Path]
            song_to_wav_path = download_audio(songs_to_process, batch_tmp, download_concurrency)

            compute_audio_embeddings(mulan, device, songs_to_process, song_to_wav_path, window_size, l2_norm)
            compute_lyrics_embeddings(mulan, device, tokenizer, songs_to_process)

            wav_paths_to_clean: List[Path] = list(song_to_wav_path.values())
            save_results_and_cleanup(songs_to_process, songs_path, processed_path, wav_paths_to_clean)

        except Exception as e:
            print(f"[batch_error] batch_idx={batch_idx} exception={e}")
        finally:
            try:
                if batch_tmp.exists():
                    if not any(batch_tmp.iterdir()):
                        batch_tmp.rmdir()
                    else:
                        print(f"Batch tmp dir not empty, left at: {batch_tmp}")
            except Exception as cleanup_err:
                print(f"[tmpdir_cleanup_warning] {batch_tmp} -> {cleanup_err}")

    print("Ingestion pipeline finished.")

# (You would also need to update save_results_and_cleanup to accept the list of paths to clean up)
def save_results_and_cleanup(songs: List[SongData], songs_path: Path, processed_path: Path, temp_wav_paths: List[Path]):
    """Saves processed data and cleans up temporary files."""
    for song in songs:
        if song.audio_status == "done" or song.lyrics_status == "done":
            try:
                append_jsonl(songs_path, song.to_song_record())
            except Exception as e:
                print(f"[ERROR] Failed to write song record for {song.song_id}: {e}")
                continue
        _log_processed_record(processed_path, song)

    # Cleanup
    for path in temp_wav_paths:
        if path and path.exists():
            try:
                os.remove(path)
            except OSError as e:
                print(f"[Warning] Failed to remove temp file {path}: {e}")
    torch.cuda.empty_cache()


def load_processed_statuses(processed_path: Path) -> Dict[str, Dict[str, str]]:
    """Loads the processed ledger into a dictionary for quick lookups."""
    statuses = {}
    if processed_path.exists():
        for record in read_jsonl(processed_path):
            song_id = record.get("song_id")
            if song_id:
                statuses[song_id] = {
                    "audio_status": record.get("audio_status"),
                    "lyrics_status": record.get("lyrics_status"),
                }
    return statuses


def custom_truncate_tokenize(tokenizer, text, max_length=512):
    encoded = tokenizer(
        text,
        padding='max_length',
        truncation=True,
        max_length=max_length,
        return_tensors='pt'
    )
    return encoded['input_ids'], encoded['attention_mask']

def compute_lyrics_embeddings(mulan, device, tokenizer, songs_batch: List[SongData]):
    lyrics_texts = []
    valid_indices = []

    # Step 1: Gather lyrics and handle per-song errors
    for idx, song in enumerate(songs_batch):
        try:
            lyrics = get_lyrics(song.title, song.artist)
            if lyrics:
                lyrics_texts.append(lyrics)
                valid_indices.append(idx)
                song.lyrics_text = lyrics  # Store for record
            else:
                song.lyrics_status = "failed"
                song.failure_reason = "lyrics_not_found"
        except Exception as e:
            song.lyrics_status = "failed"
            song.failure_reason = f"lyrics_fetch_failed: {str(e)}"

    if not lyrics_texts:
        return  # Nothing to process

    # Step 2: Batch tokenize and embed with error catch
    try:
        input_ids, attention_mask = custom_truncate_tokenize(tokenizer, lyrics_texts, max_length=512)
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)

        with torch.no_grad():
            text_embeds, _ = mulan.mulan.text(x=input_ids, mask=attention_mask, return_all_layers=True)
            text_latents = mulan.mulan.text_to_latents(text_embeds)
            emb_output = mulan.mulan._norm_latents(text_latents)

        # Step 3: Assign embeddings back, with optional per-song try/except
        for i, idx in enumerate(valid_indices):
            try:
                emb_np = emb_output[i].cpu().numpy()
                songs_batch[idx].lyrics_embedding = l2_normalize(emb_np)
                songs_batch[idx].lyrics_status = "done"
            except Exception as e:
                songs_batch[idx].lyrics_status = "failed"
                songs_batch[idx].failure_reason = f"embedding_assignment_failed: {str(e)}"

    except Exception as e:
        # If the batch model/tokenizer fails, mark all as failed
        for idx in valid_indices:
            songs_batch[idx].lyrics_status = "failed"
            songs_batch[idx].failure_reason = f"batch_embedding_failed: {str(e)}"

def _log_processed_record(processed_path: Path, song: SongData):
    """Helper to append a record to the processed.jsonl file."""
    processed_record = {
        "song_id": song.song_id,
        "title": song.title,
        "artist": song.artist,
        "processed_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "audio_status": song.audio_status,
        "lyrics_status": song.lyrics_status,
        "reason": song.failure_reason
    }
    append_jsonl(processed_path, processed_record)

run_ingestion_pipeline()

"""## Inspect data"""

# Print processed lines (tail)
print("=== processed.jsonl tail ===")
for line in read_jsonl(PROCESSED_PATH)[-20:]:
    print(line)

MAX_LYRICS_CHARS = 50

print("\n=== songs.jsonl tail ===")
for song in read_jsonl(SONGS_PATH)[-20:]:
    # make a shallow copy so we don't modify the original
    display_song = song.copy()

    for key in ["audio_embedding", "lyrics_embedding"]:
        if display_song.get(key) is not None:
            emb = display_song[key]
            # show first value, then number of remaining floats
            display_song[key] = [emb[0], f"{len(emb)-1} more floats"]

    # Truncate lyrics for display
    if display_song.get("lyrics"):
        lyrics = display_song["lyrics"]
        if len(lyrics) > MAX_LYRICS_CHARS:
            display_song["lyrics"] = lyrics[:MAX_LYRICS_CHARS] + "…"

    print(display_song)

"""# Integrating with ChromaDB"""

songs = read_jsonl(SONGS_PATH)

"""# Search functionality (Lexical FTS)"""

import re
import unicodedata
from typing import List, Dict, Any
import chromadb

# ---------- Init collections ----------
def init_collections(client: chromadb.Client,
                     lyrics_collection_name: str = "lyrics_embeddings",
                     audio_collection_name: str = "audio_embeddings",
                     metadata: Optional[Dict[str, Any]] = None):
    """
    Creates or gets the collections. We store textual searchable content in lyrics_collection.document.
    Keep audio collection metadata minimal.
    """
    # persistent directory optional: when using Settings(persist_directory="...") at client creation.
    lyrics_col = client.get_or_create_collection(name=lyrics_collection_name)
    audio_col = client.get_or_create_collection(name=audio_collection_name)
    return lyrics_col, audio_col

# ---------- utility ----------------
def normalize_text(s: str) -> str:
    """Normalize for reliable substring search: unicode NFKD, lowercase, collapse whitespace."""
    if s is None:
        return ""
    s = unicodedata.normalize("NFKD", s)
    s = s.lower()
    s = re.sub(r"\s+", " ", s).strip()
    return s

# ---------- ingestion example -------------
def ingest_song_to_chroma(client: chromadb.Client, song: Dict[str, Any],
                          lyrics_collection_name: str = "lyrics_embeddings",
                          audio_collection_name: str = "audio_embeddings"):
    """
    song is a dict like the lines of your songs.jsonl:
      { "song_id": "...", "title": "...", "artist": "...", "lyrics": "...",
        "audio_embedding": [...], "lyrics_embedding": [...], "duration": ..., "num_chunks": ... }
    """
    sid = song["song_id"]
    title = song.get("title", "")
    artist = song.get("artist", "")
    lyrics = song.get("lyrics", "")

    # canonical searchable document (normalized)
    search_doc = normalize_text(f"{title} — {artist}\n\n{lyrics}")

    # add to lyrics collection (store small preview in metadata)
    # we store text related items in lyrics for FTS so it needs to run only on lyrics collection
    lyrics_col = client.get_or_create_collection(name=lyrics_collection_name)
    shared_metadata = {
            "title": title,
            "artist": artist,
            "processed_at": song.get("processed_at"),
            # small preview for quick UI; not the canonical searchable field (that's `document`)
            "duration": song.get("duration"),
            "num_chunks": song.get("num_chunks"),
            "lyrics_preview": lyrics[:2000]
    }

    lyrics_col.add(
        ids=[sid],
        embeddings=[song["lyrics_embedding"]],
        metadatas=[shared_metadata],
        documents=[search_doc]
    )

    # add to audio collection (minimal metadata)
    audio_col = client.get_or_create_collection(name=audio_collection_name)
    audio_col.add(
        ids=[sid],
        embeddings=[song["audio_embedding"]],
        metadatas=[shared_metadata],
        documents=[None]  # no text needed here
    )

# ---------- Lexical FTS (pure substring search + simple heuristic ranking) ----------
def lexical_fts_best_match(client: chromadb.Client,
                           query: str,
                           lyrics_collection_name: str = "lyrics_embeddings",
                           limit_candidates: int = 100,
                           return_k: int = 1) -> List[Dict[str, Any]]:
    """
    Pure lexical FTS (no model calls). Returns top `return_k` matches ordered by a small heuristic:
    - exact title / exact artist > startswith > contains > occurrences in lyrics
    Each candidate: { id, score, title, artist, snippet, metadata }
    """
    if not query or not query.strip():
        return []

    q_norm = normalize_text(query)
    col = client.get_collection(name=lyrics_collection_name)

    # get candidates whose normalized document contains the normalized query
    res = col.get(where_document={"$contains": q_norm}, limit=limit_candidates, include=["metadatas","documents"])
    ids = res.get("ids", [])
    metadatas = res.get("metadatas", [])
    documents = res.get("documents", [])

    candidates = []
    for i, sid in enumerate(ids):
        md = metadatas[i] if i < len(metadatas) else {}
        doc = documents[i] if i < len(documents) else ""
        title = md.get("title","")
        artist = md.get("artist","")

        t_norm = normalize_text(title)
        a_norm = normalize_text(artist)
        d_norm = doc or ""

        score = 0
        # title signals (heaviest)
        if t_norm == q_norm:
            score += 1000
        elif t_norm.startswith(q_norm):
            score += 700
        elif q_norm in t_norm:
            score += 500

        # artist signals
        if a_norm == q_norm:
            score += 600
        elif a_norm.startswith(q_norm):
            score += 400
        elif q_norm in a_norm:
            score += 200

        # lyrics occurrences give signal but are weaker
        occ = d_norm.count(q_norm)
        score += min(occ, 10) * 20

        # token overlap bonus
        q_tokens = set(q_norm.split())
        score += len(q_tokens.intersection(set(t_norm.split()))) * 10
        score += len(q_tokens.intersection(set(a_norm.split()))) * 6

        # snippet: show surrounding text for UI if found in document
        snippet = None
        idx = d_norm.find(q_norm)
        if idx != -1:
            start = max(0, idx - 120)
            end = min(len(d_norm), idx + len(q_norm) + 120)
            snippet = d_norm[start:end]
        else:
            snippet = title or artist

        candidates.append({
            "id": sid,
            "score": score,
            "title": title,
            "artist": artist,
            "snippet": snippet,
            "metadata": md
        })

    # sort desc: higher score = better
    candidates.sort(key=lambda x: x["score"], reverse=True)
    return candidates[:return_k]

# ---------- helper: fetch audio metadata by ids -------------
def fetch_audio_metadatas(client: chromadb.Client, ids: List[str], audio_collection_name: str = "audio_embeddings") -> Dict[str, Dict]:
    col = client.get_collection(name=audio_collection_name)
    res = col.get(ids=ids, include=["metadatas"])
    ids_res = res.get("ids", [])
    metas = res.get("metadatas", [])
    return {ids_res[i]: metas[i] for i in range(len(ids_res))}

"""# Ingest from jsonl into ChromaDB"""

def sanitize_embedding(emb, dim=512):
    """
    Ensure embedding is a proper 1D numeric array.
    If missing or invalid, returns None.
    """
    if emb is None:
        return None
    arr = np.array(emb, dtype=np.float32)
    if arr.shape != (dim,):
        return None
    return arr

# ---------- Bulk ingest (idempotent using upsert) ----------
def ingest_songs_bulk(client: chromadb.Client,
                      songs: List[SongData],
                      lyrics_collection_name: str = "lyrics_embeddings",
                      audio_collection_name: str = "audio_embeddings",
                      batch_size: int = 256):
    """
    Bulk upsert songs into Chroma. Stores normalized searchable string in lyrics_collection.documents.
    """
    lyrics_col = client.get_or_create_collection(name=lyrics_collection_name)
    audio_col = client.get_or_create_collection(name=audio_collection_name)

    # Prepare batches
    ids_batch = []
    lyrics_emb_batch = []
    lyrics_meta_batch = []
    lyrics_doc_batch = []

    audio_ids_batch = []
    audio_emb_batch = []
    audio_meta_batch = []
    audio_doc_batch = []

    def flush():
        if ids_batch:
            # upsert to be idempotent (overwrites if id exists)
            lyrics_col.upsert(
                ids=ids_batch,
                embeddings=lyrics_emb_batch,
                metadatas=lyrics_meta_batch,
                documents=lyrics_doc_batch
            )
        if audio_ids_batch:
            audio_col.upsert(
                ids=audio_ids_batch,
                embeddings=audio_emb_batch,
                metadatas=audio_meta_batch,
                documents=audio_doc_batch
            )

    for s in songs:
        lyrics_emb = sanitize_embedding(s.get("lyrics_embedding"))
        audio_emb  = sanitize_embedding(s.get("audio_embedding"))

        # skip song if either embedding is missing
        if lyrics_emb is None or audio_emb is None:
            print(f"Skipping song {s['song_id']} due to invalid embedding")
            continue

        lyrics_emb_batch.append(lyrics_emb)
        audio_emb_batch.append(audio_emb)

        # build normalized searchable document: title + artist + lyrics
        search_doc = normalize_text(f"{s['title']} — {s['artist']}\n\n{s['lyrics']}")

        # lyrics collection entries
        ids_batch.append(s["song_id"])
        shared_metadata = {
            "title": s["title"],
            "artist": s["artist"],
            "processed_at": s["processed_at"],
            # small preview for quick UI; not the canonical searchable field (that's `document`)
            "duration": s["duration"],
            "num_chunks": s["num_chunks"],
            "lyrics_preview": (s["lyrics"][:2000] if s["lyrics"] else "")
        }
        #lyrics_emb_batch.append(s["lyrics_embedding"])
        lyrics_meta_batch.append(shared_metadata)
        lyrics_doc_batch.append(search_doc)

        # audio collection entries (minimal)
        audio_ids_batch.append(s["song_id"])
        #audio_emb_batch.append(s["audio_embedding"])
        audio_meta_batch.append(shared_metadata)
        audio_doc_batch.append(None)

        # flush in batches
        if len(ids_batch) >= batch_size:
            flush()
            ids_batch.clear(); lyrics_emb_batch.clear(); lyrics_meta_batch.clear(); lyrics_doc_batch.clear()
            audio_ids_batch.clear(); audio_emb_batch.clear(); audio_meta_batch.clear(); audio_doc_batch.clear()

    # final flush
    flush()

# Create client (in Colab you can persist to a folder if desired)
client = chromadb.PersistentClient(path="/content/chroma_db/")

# initialize collections
init_collections(client)

ingest_songs_bulk(client, songs)

# example FTS query:
q = "von dutch"
results = lexical_fts_best_match(client, q, return_k=3)
print("FTS results:", results)

# if you want to get audio metadata for a matched song id:
if results:
    matched_id = results[0]["id"]
    audio_meta = fetch_audio_metadatas(client, [matched_id])
    print("audio metadata:", audio_meta)

results[0]

import numpy as np

def weighted_modal_search(client,
                          song_id: str,
                          alpha: float = 0.5,
                          limit_candidates: int = 50,
                          return_k: int = 10,
                          lyrics_collection_name: str = "lyrics_embeddings",
                          audio_collection_name: str = "audio_embeddings"):
    """
    Weighted multi-modal search for songs given a song_id.
    alpha=1 -> audio only, alpha=0 -> lyrics only
    Returns top `return_k` songs.
    Assumes embeddings are already L2-normalized.
    """
    # --- Fetch collections ---
    lyrics_col = client.get_collection(name=lyrics_collection_name)
    audio_col  = client.get_collection(name=audio_collection_name)

    # --- Fetch embeddings for query song ---
    lyrics_res = lyrics_col.get(ids=[song_id], include=["embeddings"])
    audio_res  = audio_col.get(ids=[song_id], include=["embeddings"])

    lyrics_emb = np.array(lyrics_res["embeddings"][0]) if len(lyrics_res.get("embeddings", [])) > 0 else None
    audio_emb  = np.array(audio_res["embeddings"][0])  if len(audio_res.get("embeddings", [])) > 0 else None

    # --- Handle missing modalities for query ---
    if lyrics_emb is None and audio_emb is None:
        raise ValueError(f"Both modalities missing for {song_id}")
    if lyrics_emb is None:
        alpha = 1.0
        query_emb = audio_emb
    elif audio_emb is None:
        alpha = 0.0
        query_emb = lyrics_emb
    else:
        query_emb = alpha * audio_emb + (1 - alpha) * lyrics_emb

    # Normalize query embedding
    q_norm = np.linalg.norm(query_emb)
    if q_norm == 0:
        raise ValueError("Query embedding has zero norm (invalid embedding)")
    query_emb = query_emb / q_norm

    # --- Fetch candidate sets ---
    lyrics_cand = lyrics_col.query(
        query_embeddings=[lyrics_emb] if lyrics_emb is not None else None,
        n_results=limit_candidates,
        include=["embeddings", "metadatas"]
    ) if lyrics_emb is not None else {"ids": [], "embeddings": [], "metadatas": []}

    audio_cand = audio_col.query(
        query_embeddings=[audio_emb] if audio_emb is not None else None,
        n_results=limit_candidates,
        include=["embeddings", "metadatas"]
    ) if audio_emb is not None else {"ids": [], "embeddings": [], "metadatas": []}

    # --- Extract lists safely ---
    lyrics_ids   = lyrics_cand["ids"][0] if len(lyrics_cand.get("ids", [])) > 0 else []
    lyrics_embs  = lyrics_cand["embeddings"][0] if len(lyrics_cand.get("embeddings", [])) > 0 else []
    lyrics_metas = lyrics_cand["metadatas"][0] if len(lyrics_cand.get("metadatas", [])) > 0 else []

    audio_ids    = audio_cand["ids"][0] if len(audio_cand.get("ids", [])) > 0 else []
    audio_embs   = audio_cand["embeddings"][0] if len(audio_cand.get("embeddings", [])) > 0 else []
    audio_metas  = audio_cand["metadatas"][0] if len(audio_cand.get("metadatas", [])) > 0 else []

    # --- Merge candidates into a unified dict ---
    cand_dict = {}

    for i, sid in enumerate(lyrics_ids):
        if sid == song_id:
            continue
        cand_dict[sid] = {
            "lyrics_emb": np.array(lyrics_embs[i]),
            "audio_emb": None,
            "lyrics_metadata": lyrics_metas[i] or {},
            "audio_metadata": {}
        }

    for i, sid in enumerate(audio_ids):
        if sid == song_id:
            continue
        if sid in cand_dict:
            cand_dict[sid]["audio_emb"] = np.array(audio_embs[i])
            cand_dict[sid]["audio_metadata"] = audio_metas[i] or {}
        else:
            cand_dict[sid] = {
                "lyrics_emb": None,
                "audio_emb": np.array(audio_embs[i]),
                "lyrics_metadata": {},
                "audio_metadata": audio_metas[i] or {}
            }

    # --- Build final merged candidate list with weighted similarity ---
    canonical_keys = ["title", "artist", "processed_at", "lyrics_preview", "duration", "num_chunks"]
    merged_candidates = []

    for sid, data in cand_dict.items():
        l_emb = data["lyrics_emb"]
        a_emb = data["audio_emb"]

        # Determine merged embedding per song
        if l_emb is None:
            merged_emb = a_emb
        elif a_emb is None:
            merged_emb = l_emb
        else:
            merged_emb = alpha * a_emb + (1 - alpha) * l_emb

        # Compute similarity
        if merged_emb is None:
            sim = -1.0
        else:
            m_norm = np.linalg.norm(merged_emb)
            if m_norm == 0:
                sim = -1.0
            else:
                merged_emb = merged_emb / m_norm
                sim = float(np.dot(query_emb, merged_emb))

        # Merge metadata
        combined = {**(data.get("audio_metadata") or {}), **(data.get("lyrics_metadata") or {})}
        canonical = {k: combined.get(k) for k in canonical_keys}
        extra = {k: v for k, v in combined.items() if k not in canonical_keys}
        if extra:
            canonical["extra_metadata"] = extra

        merged_candidates.append({
            "id": sid,
            "metadata": canonical,
            "similarity": sim
        })

    # --- Sort by similarity and return top k ---
    merged_candidates.sort(key=lambda x: x["similarity"], reverse=True)
    return merged_candidates[:return_k]

results[0]["id"]

weighted_modal_search(client, "yt:cwZ1L_0QLjw", 1)

def search_closest_songs(client, q, alpha=0.5, return_k=10):
    results = lexical_fts_best_match(client, q, return_k=1)

    if results:
        matched_id = results[0]["id"]
        return weighted_modal_search(client, results[0]["id"], alpha, return_k=return_k)

# IMPORTANT: schema mismatch???
matches = [{m['id'], m['metadata']['title'], m['metadata']['artist']} for m in search_closest_songs(client, "von dutch", alpha=1)]
matches

for m in search_closest_songs(client, "von dutch", alpha=1, return_k=5):
  print(m)

!rm manifest.jsonl processed.jsonl songs.jsonl

import shutil
from google.colab import files

# path to your Chroma DB folder
chroma_folder = "/content/chroma_db"
zip_path = "/content/chroma_db.zip"

# create a zip archive
shutil.make_archive(base_name=zip_path.replace(".zip", ""), format="zip", root_dir=chroma_folder)

# download the zip
files.download(zip_path)

"""# Load from sql file"""

from chromadb import PersistentClient
from chromadb.config import Settings

def load_chroma_db_from_folder(folder_path: str) -> PersistentClient:
    """
    Load an existing ChromaDB instance from a folder containing the SQLite file.
    """
    client = PersistentClient(path=folder_path)
    return client

!unzip chroma_db.zip -d /content/chroma_db

client = load_chroma_db_from_folder("/content/chroma_db")

# example FTS query:
q = "von dutch"
results = lexical_fts_best_match(client, q, return_k=3)
print("FTS results:", results)

# if you want to get audio metadata for a matched song id:
if results:
    matched_id = results[0]["id"]
    audio_meta = fetch_audio_metadatas(client, [matched_id])
    print("audio metadata:", audio_meta)

weighted_modal_search(client, results[0]["id"], 1)

for song in songs:
    print(f"{song["song_id"]}: {song['title']} - {song['artist']}")

results = lexical_fts_best_match(client, "smiths", return_k=3)
for result in results:
    print(result)

import numpy as np

def weighted_modal_search_interpolate(client,
                                      query_emb: np.ndarray = None,
                                      skip_ids: list = None,
                                      alpha: float = 0.5,
                                      limit_candidates: int = 50,
                                      return_k: int = 10,
                                      lyrics_collection_name: str = "lyrics_embeddings",
                                      audio_collection_name: str = "audio_embeddings"):
    """
    Weighted multi-modal search for songs given a query embedding directly.
    query_emb: np.array, merged embedding or any custom query vector.
    skip_ids: list of song ids to skip (e.g., already used in interpolation)
    alpha: weighting between audio and lyrics
    Returns top `return_k` songs with similarity scores.
    """
    skip_ids = set(skip_ids or [])

    # --- Fetch collections ---
    lyrics_col = client.get_collection(name=lyrics_collection_name)
    audio_col  = client.get_collection(name=audio_collection_name)

    # --- Determine if we have a query embedding ---
    if query_emb is None:
        raise ValueError("query_emb must be provided.")

    # Normalize query embedding
    q_norm = np.linalg.norm(query_emb)
    if q_norm == 0:
        raise ValueError("Query embedding has zero norm (invalid embedding)")
    query_emb = query_emb / q_norm

    # --- Fetch candidate sets ---
    lyrics_cand = lyrics_col.query(
        query_embeddings=[query_emb],
        n_results=limit_candidates,
        include=["embeddings", "metadatas"]
    ) or {"ids": [], "embeddings": [], "metadatas": []}

    audio_cand = audio_col.query(
        query_embeddings=[query_emb],
        n_results=limit_candidates,
        include=["embeddings", "metadatas"]
    ) or {"ids": [], "embeddings": [], "metadatas": []}

    # --- Extract lists safely ---
    lyrics_ids   = lyrics_cand["ids"][0] if len(lyrics_cand.get("ids", [])) > 0 else []
    lyrics_embs  = lyrics_cand["embeddings"][0] if len(lyrics_cand.get("embeddings", [])) > 0 else []
    lyrics_metas = lyrics_cand["metadatas"][0] if len(lyrics_cand.get("metadatas", [])) > 0 else []

    audio_ids    = audio_cand["ids"][0] if len(audio_cand.get("ids", [])) > 0 else []
    audio_embs   = audio_cand["embeddings"][0] if len(audio_cand.get("embeddings", [])) > 0 else []
    audio_metas  = audio_cand["metadatas"][0] if len(audio_cand.get("metadatas", [])) > 0 else []

    # --- Merge candidates into a unified dict ---
    cand_dict = {}

    for i, sid in enumerate(lyrics_ids):
        if sid in skip_ids:
            continue
        cand_dict[sid] = {
            "lyrics_emb": np.array(lyrics_embs[i]),
            "audio_emb": None,
            "lyrics_metadata": lyrics_metas[i] or {},
            "audio_metadata": {}
        }

    for i, sid in enumerate(audio_ids):
        if sid in skip_ids:
            continue
        if sid in cand_dict:
            cand_dict[sid]["audio_emb"] = np.array(audio_embs[i])
            cand_dict[sid]["audio_metadata"] = audio_metas[i] or {}
        else:
            cand_dict[sid] = {
                "lyrics_emb": None,
                "audio_emb": np.array(audio_embs[i]),
                "lyrics_metadata": {},
                "audio_metadata": audio_metas[i] or {}
            }

    # --- Build final merged candidate list with weighted similarity ---
    canonical_keys = ["title", "artist", "processed_at", "lyrics_preview", "duration", "num_chunks"]
    merged_candidates = []

    for sid, data in cand_dict.items():
        l_emb = data["lyrics_emb"]
        a_emb = data["audio_emb"]

        # Determine merged embedding per song
        if l_emb is None:
            merged_emb = a_emb
        elif a_emb is None:
            merged_emb = l_emb
        else:
            merged_emb = alpha * a_emb + (1 - alpha) * l_emb

        if merged_emb is None:
            continue

        # Normalize merged embedding
        m_norm = np.linalg.norm(merged_emb)
        if m_norm == 0:
            continue
        merged_emb = merged_emb / m_norm

        # Compute similarity
        sim = float(np.dot(query_emb, merged_emb))

        # Merge metadata
        combined = {**(data.get("audio_metadata") or {}), **(data.get("lyrics_metadata") or {})}
        canonical = {k: combined.get(k) for k in canonical_keys}
        extra = {k: v for k, v in combined.items() if k not in canonical_keys}
        if extra:
            canonical["extra_metadata"] = extra

        merged_candidates.append({
            "id": sid,
            "metadata": canonical,
            "similarity": sim
        })

    # --- Sort by similarity and return top k ---
    merged_candidates.sort(key=lambda x: x["similarity"], reverse=True)
    return merged_candidates[:return_k]


# ==========================================
# Interpolation Function
# ==========================================

def interpolate_songs(client,
                      source_song_id: str,
                      destination_song_id: str,
                      k: int,
                      alpha: float = 0.5,
                      limit_candidates: int = 50,
                      lyrics_collection_name: str = "lyrics_embeddings",
                      audio_collection_name: str = "audio_embeddings"):
    """
    Interpolate between source and destination songs, returning k songs in between.
    Uses weighted multi-modal embeddings and linear interpolation in embedding space.
    """
    # --- Fetch merged embeddings for source and destination ---
    def get_merged_embedding(song_id):
        lyrics_col = client.get_collection(name=lyrics_collection_name)
        audio_col  = client.get_collection(name=audio_collection_name)
        lyrics_res = lyrics_col.get(ids=[song_id], include=["embeddings", "metadatas"])
        audio_res  = audio_col.get(ids=[song_id], include=["embeddings", "metadatas"])
        lyrics_emb = np.array(lyrics_res["embeddings"][0]) if len(lyrics_res.get("embeddings", [])) > 0 else None
        audio_emb  = np.array(audio_res["embeddings"][0])  if len(audio_res.get("embeddings", [])) > 0 else None

        if lyrics_emb is None and audio_emb is None:
            raise ValueError(f"Both modalities missing for {song_id}")

        # Fallback for alpha if requested modality missing
        if alpha >= 0.5 and audio_emb is None:
            print(f"Warning: Audio missing for {song_id}, using lyrics instead.")
            merged = lyrics_emb
        elif alpha < 0.5 and lyrics_emb is None:
            print(f"Warning: Lyrics missing for {song_id}, using audio instead.")
            merged = audio_emb
        else:
            # Compute weighted embedding
            merged = (alpha * audio_emb if audio_emb is not None else 0.0) + \
                     ((1-alpha) * lyrics_emb if lyrics_emb is not None else 0.0)

        # Normalize
        norm = np.linalg.norm(merged)
        if norm == 0:
            raise ValueError(f"Song {song_id} has zero norm embedding.")
        return merged / norm

    source_emb = get_merged_embedding(source_song_id)
    dest_emb   = get_merged_embedding(destination_song_id)

    # Check if source and destination are identical
    if np.allclose(source_emb, dest_emb):
        raise ValueError("Source and destination embeddings are identical; cannot interpolate.")

    # --- Compute unit step vector ---
    delta = dest_emb - source_emb
    step_vector = delta / (k + 1)

    # --- Interpolation loop ---
    used_ids = set([source_song_id, destination_song_id])
    interpolated_songs = []

    # Add source song
    interpolated_songs.append({"id": source_song_id, "embedding": source_emb})

    for i in range(1, k + 1):
        query_emb = source_emb + i * step_vector
        # Check for zero vector
        if np.linalg.norm(query_emb) == 0:
            print(f"Warning: Step {i} produced zero vector; skipping.")
            continue

        # Find nearest song not in used_ids
        result = weighted_modal_search_interpolate(
            client,
            query_emb=query_emb,
            skip_ids=list(used_ids),
            alpha=alpha,
            limit_candidates=limit_candidates,
            return_k=1,
            lyrics_collection_name=lyrics_collection_name,
            audio_collection_name=audio_collection_name
        )

        if result:
            interpolated_songs.append(result[0])
            used_ids.add(result[0]["id"])
        else:
            print(f"Warning: No candidate found for step {i}.")

    # Add destination song
    interpolated_songs.append({"id": destination_song_id, "embedding": dest_emb})

    return interpolated_songs

source = "yt:cwZ1L_0QLjw" # Von dutch - Charli xcx
destination = "yt:3r-qDvD3F3c" # There Is a Light That Never Goes Out - The Smiths

input = ["yt:R2-yomhYAj4", "yt:XFkzRNyygfk"]
source = input[0]
destination = input[1]

# Parameters
k = 5          # Number of songs to interpolate in between
alpha = 1.0    # Weight towards audio modality
limit_candidates = 50  # Number of candidates to fetch per step

# Run interpolation
interpolated_playlist = interpolate_songs(
    client=client,
    source_song_id=source,
    destination_song_id=destination,
    k=k,
    alpha=alpha,
    limit_candidates=limit_candidates
)

# Print results
for idx, song in enumerate(interpolated_playlist):
    print(f"Step {idx}:")
    print(f"  ID: {song['id']}")
    if "metadata" in song:
        print(f"  Title: {song['metadata'].get('title')}")
        print(f"  Artist: {song['metadata'].get('artist')}")
    if "similarity" in song:
        print(f"  Similarity: {song['similarity']:.4f}")
    print("-" * 40)

import numpy as np
from itertools import combinations

def find_most_dissimilar_songs(audio_col):
    """
    Finds the two most dissimilar songs in the audio collection.
    Assumes embeddings are L2-normalized.
    """
    # fetch all audio embeddings and IDs
    all_data = audio_col.get(include=["embeddings"])
    ids = all_data["ids"]
    embeddings = np.array(all_data["embeddings"])  # shape: (num_songs, 512)

    # initialize
    min_sim = float("inf")
    song_pair = (None, None)

    # brute force pairwise comparison
    for i, j in combinations(range(len(ids)), 2):
        sim = np.dot(embeddings[i], embeddings[j])  # cosine similarity
        if sim < min_sim:
            min_sim = sim
            song_pair = (ids[i], ids[j])

    print(f"Most dissimilar songs: {song_pair} with similarity {min_sim:.4f}")
    return song_pair, min_sim

audio_col = client.get_collection("audio_embeddings")
find_most_dissimilar_songs(audio_col)

client.get_collection("audio_embeddings").get(ids=["yt:R2-yomhYAj4", "yt:XFkzRNyygfk"])